#!/bin/sh

# npm install -g forever
# sudo ln -s /usr/local/bin/node/bin/node /usr/bin/node
# in /etc/rc.local, add..
# sudo -u ec2-user /home/ec2-user/cats/serve

cd /home/ec2-user/cats

/usr/local/bin/node/bin/forever stop server.js
/usr/local/bin/node/bin/forever start server.js
